# Generated by Django 5.1.5 on 2025-02-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
