# Generated by Django 5.1.5 on 2025-02-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
