# Generated by Django 5.1.5 on 2025-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="expiry_date",
            field=models.DateField(null=True),
        ),
    ]
