# Generated by Django 5.1.5 on 2025-01-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="reorder_level",
            field=models.IntegerField(default=10),
        ),
    ]
