# Generated by Django 5.1.5 on 2025-01-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventory_reorder_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptitem",
            name="reorder_level",
            field=models.IntegerField(default=10),
        ),
    ]
