# Generated by Django 5.1.5 on 2025-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventory_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="expiry_date",
            field=models.DateField(),
        ),
    ]
