# Generated by Django 5.1.5 on 2025-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_receiptitem_reorder_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptitem",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
