# Generated by Django 5.1.5 on 2025-02-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_inventory_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptitem",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiptitem_set",
                to="inventory.receipt",
            ),
        ),
    ]
