# Generated by Django 5.1.5 on 2025-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_receiptitem_purchase_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptitem",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
