# Generated by Django 5.1.5 on 2025-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_receiptitem_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
