# Generated by Django 5.1.5 on 2025-01-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_receiptitem_purchase_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="selling_price",
        ),
        migrations.RenameField(
            model_name="receiptitem",
            old_name="price",
            new_name="cost_price",
        ),
        migrations.RenameField(
            model_name="receiptitem",
            old_name="purchase_price",
            new_name="selling_price",
        ),
    ]
