# Generated by Django 5.1.5 on 2025-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventory_selling_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
